services:
  django:
    build:
      context: ./django/ringSignatureBP
    volumes:
      - ./django/ringSignatureBP:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - django
    restart: always

  tor:
    build: ./tor
    volumes:
      - ./tor/hidden_service:/var/lib/tor/hidden_service
    depends_on:
      - nginx
    restart: unless-stopped